# adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - bash: C:\MinGW\msys\1.0\bin\bash
    - bash: C:\cygwin\bin\bash
matrix:
  fast_finish: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - cmd: choco install sbt -ia "INSTALLDIR=""C:\sbt"""
  - cmd: SET PATH=C:\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - ps: $url = get-content artifacts | select-string "zip" | Foreach {($_ -split  '=', 2)[1]};  wget -O dotty.zip $url
  - ps: Expand-Archive dotty.zip -DestinationPath dotty
test_script:
  - ps: cd dotty-*; $env:bash bin\dotc ..\examples\HelloWorld.scala
  - ps: cd dotty-*; $env:bash bin\dotr HelloWorld
  - ps: cd dotty-*; $env:bash bin\dotd ..\examples\HelloWorld.scala

