# adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - bash: C:\MinGW\msys\1.0\bin
    - bash: C:\cygwin\bin
matrix:
  fast_finish: true

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
build_script:
  - ps: $url = get-content artifacts | select-string "zip" | Foreach {($_ -split  '=', 2)[1]};  wget -O scala3.zip $url
  - ps: Expand-Archive scala3.zip -DestinationPath .
  - cmd: SET PATH=%bash%;%PATH%
test_script:
  - cmd: bash windows

