matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: java
    - os: linux
      language: scala
      jdk: oraclejdk8
script:
  - source artifacts && wget -O dotty.tar.gz $tar
  - tar -xzvf dotty.tar.gz --strip-components=1
  - bin/dotc @examples/options examples/HelloWorld.scala
  - bin/dotc examples/HelloWorld.scala
  - bin/dotr dotty.HelloWorld
  - bin/dotr -J-Xmx512m dotty.HelloWorld
  - echo ":quit" | bin/dotr
  - echo ":quit" | bin/dotr -language:Scala2
  - mkdir -p _site && bin/dotd -siteroot _site -project Hello examples/HelloWorld.scala
