matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: java
    - os: linux
      language: scala
      jdk: oraclejdk8
script:
  - wget -O dotty.tar.gz https://github.com/lampepfl/dotty/releases/download/0.1.2-RC1/dotty-0.1.2-RC1.tar.gz
  - tar -xzvf dotty.tar.gz --strip-components=1
  - bin/dotc examples/HelloWorld.scala
  - bin/dotr HelloWorld
  - bin/dotd examples/HelloWorld.scala

