matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      language: java
    - os: linux
      language: scala
      jdk: openjdk8
script:
  - source artifacts && wget -O scala3.tar.gz $tar
  - tar -xzvf scala3.tar.gz --strip-components=1
  - bin/scalac @examples/options examples/HelloWorld.scala
  - bin/scalac examples/HelloWorld.scala
  - bin/scala dotty.HelloWorld
  - bin/scala -J-Xmx512m dotty.HelloWorld
  # - echo ":quit" | bin/dotr                      # not usable in test env, jline crash
  # - echo ":quit" | bin/dotr -language:Scala2     # see above
  - mkdir -p _site && bin/scaladoc -siteroot _site -project Hello examples/HelloWorld.scala
